apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-test-app-1
  description: A python application as a test component named - python-test-app-1
  annotations:
    github.com/project-slug: kezri-29/python-test-app-1
    backstage.io/techdocs-ref: dir:.
    scorecard/jsonDataUrl: https://raw.githubusercontent.com/kezri-29/python-test-app-1/refs/heads/main/component-score.json
    argocd/app-name: python-test-app-1
spec:
  type: service
  owner: development
  lifecycle: experimental
